name: meno_design_system
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  pinput: ^3.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: MIcons
      fonts:
        - asset: assets/fonts/MIcons.ttf
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay_Thin.ttf
          weight: 100
        - asset: assets/fonts/SFProDisplay_UltraLight.ttf
          weight: 200
        - asset: assets/fonts/SFProDisplay_Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay_Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay_Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay_Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay_Black.ttf
          weight: 800
        - asset: assets/fonts/SFProDisplay_Heavy.ttf
          weight: 900