name: meno_fe_v1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations
    - assets/brand
    - assets/fonts
    - assets/images
  
  fonts:
    - family: MIcons
      fonts:
        - asset: assets/fonts/MIcons.ttf
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay_Thin.ttf
          weight: 100
        - asset: assets/fonts/SFProDisplay_UltraLight.ttf
          weight: 200
        - asset: assets/fonts/SFProDisplay_Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay_Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay_Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay_Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay_Black.ttf
          weight: 800
        - asset: assets/fonts/SFProDisplay_Heavy.ttf
          weight: 900