name: meno
publish_to: none
environment:
  sdk: ^3.9.2
workspace:
  - apps/meno_app
  - packages/meno_auth
  - packages/meno_design_system
  - packages/meno_domain
  - packages/meno_onboarding
dev_dependencies:
  melos: ^7.3.0
