// Mocks generated by Mockito 5.4.6 from annotations
// in meno/test/features/auth/widgets/login_form_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter/foundation.dart' as _i2;
import 'package:flutter_it/flutter_it.dart' as _i3;
import 'package:meno/_core/_core.dart' as _i5;
import 'package:meno/_shared/_shared.dart' as _i6;
import 'package:meno/features/auth/auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValueListenable_0<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommand_1<TParam, TResult> extends _i1.SmartFake
    implements _i3.Command<TParam, TResult> {
  _FakeCommand_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthManager extends _i1.Mock implements _i4.AuthManager {
  MockAuthManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueListenable<_i5.Id> get activeUserId =>
      (super.noSuchMethod(
            Invocation.getter(#activeUserId),
            returnValue: _FakeValueListenable_0<_i5.Id>(
              this,
              Invocation.getter(#activeUserId),
            ),
          )
          as _i2.ValueListenable<_i5.Id>);

  @override
  _i2.ValueListenable<Map<_i5.Id, _i4.UserCredential>> get accounts =>
      (super.noSuchMethod(
            Invocation.getter(#accounts),
            returnValue:
                _FakeValueListenable_0<Map<_i5.Id, _i4.UserCredential>>(
                  this,
                  Invocation.getter(#accounts),
                ),
          )
          as _i2.ValueListenable<Map<_i5.Id, _i4.UserCredential>>);

  @override
  _i2.ValueListenable<_i6.User> get lastKnownUser =>
      (super.noSuchMethod(
            Invocation.getter(#lastKnownUser),
            returnValue: _FakeValueListenable_0<_i6.User>(
              this,
              Invocation.getter(#lastKnownUser),
            ),
          )
          as _i2.ValueListenable<_i6.User>);

  @override
  _i2.ValueListenable<bool> get pendingEmailVerification =>
      (super.noSuchMethod(
            Invocation.getter(#pendingEmailVerification),
            returnValue: _FakeValueListenable_0<bool>(
              this,
              Invocation.getter(#pendingEmailVerification),
            ),
          )
          as _i2.ValueListenable<bool>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Command<_i4.LoginArgs, _i4.UserCredential> get login =>
      (super.noSuchMethod(
            Invocation.getter(#login),
            returnValue: _FakeCommand_1<_i4.LoginArgs, _i4.UserCredential>(
              this,
              Invocation.getter(#login),
            ),
          )
          as _i3.Command<_i4.LoginArgs, _i4.UserCredential>);

  @override
  _i3.Command<_i4.RegisterArgs, _i4.UserCredential> get register =>
      (super.noSuchMethod(
            Invocation.getter(#register),
            returnValue: _FakeCommand_1<_i4.RegisterArgs, _i4.UserCredential>(
              this,
              Invocation.getter(#register),
            ),
          )
          as _i3.Command<_i4.RegisterArgs, _i4.UserCredential>);

  @override
  _i3.Command<String, _i4.UserCredential> get googleSignIn =>
      (super.noSuchMethod(
            Invocation.getter(#googleSignIn),
            returnValue: _FakeCommand_1<String, _i4.UserCredential>(
              this,
              Invocation.getter(#googleSignIn),
            ),
          )
          as _i3.Command<String, _i4.UserCredential>);

  @override
  _i3.Command<String, _i4.UserCredential> get googleSignUp =>
      (super.noSuchMethod(
            Invocation.getter(#googleSignUp),
            returnValue: _FakeCommand_1<String, _i4.UserCredential>(
              this,
              Invocation.getter(#googleSignUp),
            ),
          )
          as _i3.Command<String, _i4.UserCredential>);

  @override
  _i3.Command<void, void> get logout =>
      (super.noSuchMethod(
            Invocation.getter(#logout),
            returnValue: _FakeCommand_1<void, void>(
              this,
              Invocation.getter(#logout),
            ),
          )
          as _i3.Command<void, void>);

  @override
  _i3.Command<_i5.Id, void> get switchAccount =>
      (super.noSuchMethod(
            Invocation.getter(#switchAccount),
            returnValue: _FakeCommand_1<_i5.Id, void>(
              this,
              Invocation.getter(#switchAccount),
            ),
          )
          as _i3.Command<_i5.Id, void>);

  @override
  _i3.Command<void, void> get addAccount =>
      (super.noSuchMethod(
            Invocation.getter(#addAccount),
            returnValue: _FakeCommand_1<void, void>(
              this,
              Invocation.getter(#addAccount),
            ),
          )
          as _i3.Command<void, void>);

  @override
  _i3.Command<_i4.OtpRequestArgs, void> get requestOtp =>
      (super.noSuchMethod(
            Invocation.getter(#requestOtp),
            returnValue: _FakeCommand_1<_i4.OtpRequestArgs, void>(
              this,
              Invocation.getter(#requestOtp),
            ),
          )
          as _i3.Command<_i4.OtpRequestArgs, void>);

  @override
  _i3.Command<_i4.VerifyEmailArgs, void> get verifyEmail =>
      (super.noSuchMethod(
            Invocation.getter(#verifyEmail),
            returnValue: _FakeCommand_1<_i4.VerifyEmailArgs, void>(
              this,
              Invocation.getter(#verifyEmail),
            ),
          )
          as _i3.Command<_i4.VerifyEmailArgs, void>);

  @override
  _i3.Command<_i4.ResetPasswordArgs, void> get resetPassword =>
      (super.noSuchMethod(
            Invocation.getter(#resetPassword),
            returnValue: _FakeCommand_1<_i4.ResetPasswordArgs, void>(
              this,
              Invocation.getter(#resetPassword),
            ),
          )
          as _i3.Command<_i4.ResetPasswordArgs, void>);

  @override
  _i3.Command<_i4.ChangePasswordArgs, void> get changePassword =>
      (super.noSuchMethod(
            Invocation.getter(#changePassword),
            returnValue: _FakeCommand_1<_i4.ChangePasswordArgs, void>(
              this,
              Invocation.getter(#changePassword),
            ),
          )
          as _i3.Command<_i4.ChangePasswordArgs, void>);

  @override
  _i3.Command<void, void> get deleteAccount =>
      (super.noSuchMethod(
            Invocation.getter(#deleteAccount),
            returnValue: _FakeCommand_1<void, void>(
              this,
              Invocation.getter(#deleteAccount),
            ),
          )
          as _i3.Command<void, void>);

  @override
  set login(_i3.Command<_i4.LoginArgs, _i4.UserCredential>? value) =>
      super.noSuchMethod(
        Invocation.setter(#login, value),
        returnValueForMissingStub: null,
      );

  @override
  set register(_i3.Command<_i4.RegisterArgs, _i4.UserCredential>? value) =>
      super.noSuchMethod(
        Invocation.setter(#register, value),
        returnValueForMissingStub: null,
      );

  @override
  set googleSignIn(_i3.Command<String, _i4.UserCredential>? value) =>
      super.noSuchMethod(
        Invocation.setter(#googleSignIn, value),
        returnValueForMissingStub: null,
      );

  @override
  set googleSignUp(_i3.Command<String, _i4.UserCredential>? value) =>
      super.noSuchMethod(
        Invocation.setter(#googleSignUp, value),
        returnValueForMissingStub: null,
      );

  @override
  set logout(_i3.Command<void, void>? value) => super.noSuchMethod(
    Invocation.setter(#logout, value),
    returnValueForMissingStub: null,
  );

  @override
  set switchAccount(_i3.Command<_i5.Id, void>? value) => super.noSuchMethod(
    Invocation.setter(#switchAccount, value),
    returnValueForMissingStub: null,
  );

  @override
  set addAccount(_i3.Command<void, void>? value) => super.noSuchMethod(
    Invocation.setter(#addAccount, value),
    returnValueForMissingStub: null,
  );

  @override
  set requestOtp(_i3.Command<_i4.OtpRequestArgs, void>? value) =>
      super.noSuchMethod(
        Invocation.setter(#requestOtp, value),
        returnValueForMissingStub: null,
      );

  @override
  set verifyEmail(_i3.Command<_i4.VerifyEmailArgs, void>? value) =>
      super.noSuchMethod(
        Invocation.setter(#verifyEmail, value),
        returnValueForMissingStub: null,
      );

  @override
  set resetPassword(_i3.Command<_i4.ResetPasswordArgs, void>? value) =>
      super.noSuchMethod(
        Invocation.setter(#resetPassword, value),
        returnValueForMissingStub: null,
      );

  @override
  set changePassword(_i3.Command<_i4.ChangePasswordArgs, void>? value) =>
      super.noSuchMethod(
        Invocation.setter(#changePassword, value),
        returnValueForMissingStub: null,
      );

  @override
  set deleteAccount(_i3.Command<void, void>? value) => super.noSuchMethod(
    Invocation.setter(#deleteAccount, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
