// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxWlc4VKQSVtpv71au_3ti7O-gFfwJbUo',
    appId: '1:593476383611:web:c17bf4b321c04f04cc43de',
    messagingSenderId: '593476383611',
    projectId: 'meno-flutter',
    authDomain: 'meno-flutter.firebaseapp.com',
    storageBucket: 'meno-flutter.firebasestorage.app',
    measurementId: 'G-0VCR0LYN9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs54AAhjfyobbpR1mRfn1LJaUe9RKfXD0',
    appId: '1:593476383611:android:12ac63048c918fc6cc43de',
    messagingSenderId: '593476383611',
    projectId: 'meno-flutter',
    storageBucket: 'meno-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjZLIZQmJPxnSlj6CcKlmj8HkC5wDKM0g',
    appId: '1:593476383611:ios:0f6ddccb4e54e0bdcc43de',
    messagingSenderId: '593476383611',
    projectId: 'meno-flutter',
    storageBucket: 'meno-flutter.firebasestorage.app',
    iosBundleId: 'com.inklings.meno',
  );

}