// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs54AAhjfyobbpR1mRfn1LJaUe9RKfXD0',
    appId: '1:593476383611:android:a46bf69187c84bc8cc43de',
    messagingSenderId: '593476383611',
    projectId: 'meno-flutter',
    storageBucket: 'meno-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjZLIZQmJPxnSlj6CcKlmj8HkC5wDKM0g',
    appId: '1:593476383611:ios:59061d1e63e0407fcc43de',
    messagingSenderId: '593476383611',
    projectId: 'meno-flutter',
    storageBucket: 'meno-flutter.appspot.com',
    iosBundleId: 'com.inklings.meno',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbcx8hIQxGwcKEw87AnvOW7w8TRshCobQ',
    appId: '1:593476383611:web:e1f2ec446e2dc998cc43de',
    messagingSenderId: '593476383611',
    projectId: 'meno-flutter',
    authDomain: 'meno-flutter.firebaseapp.com',
    storageBucket: 'meno-flutter.appspot.com',
    measurementId: 'G-37XZDSBXWD',
  );

}