// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs54AAhjfyobbpR1mRfn1LJaUe9RKfXD0',
    appId: '1:593476383611:android:b068968f5dc3bae5cc43de',
    messagingSenderId: '593476383611',
    projectId: 'meno-flutter',
    storageBucket: 'meno-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjZLIZQmJPxnSlj6CcKlmj8HkC5wDKM0g',
    appId: '1:593476383611:ios:0b14332d1dc6aafdcc43de',
    messagingSenderId: '593476383611',
    projectId: 'meno-flutter',
    storageBucket: 'meno-flutter.appspot.com',
    iosBundleId: 'com.inklings.menoFeV1',
  );
}
