// Mocks generated by Mockito 5.4.6 from annotations
// in meno/test/features/auth/auth_http_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i2;
import 'package:meno/_shared/services/http_client.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCancelToken_2 extends _i1.SmartFake implements _i2.CancelToken {
  _FakeCancelToken_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get raw =>
      (super.noSuchMethod(
            Invocation.getter(#raw),
            returnValue: _FakeDio_0(this, Invocation.getter(#raw)),
          )
          as _i2.Dio);

  @override
  _i3.Future<T> get<T>(
    String? path, {
    required _i4.FromJson<T>? fromJson,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
    bool? retry = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #fromJson: fromJson,
                #queryParameters: queryParameters,
                #headers: headers,
                #cancelToken: cancelToken,
                #retry: retry,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #get,
                      [path],
                      {
                        #fromJson: fromJson,
                        #queryParameters: queryParameters,
                        #headers: headers,
                        #cancelToken: cancelToken,
                        #retry: retry,
                      },
                    ),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(
                    #get,
                    [path],
                    {
                      #fromJson: fromJson,
                      #queryParameters: queryParameters,
                      #headers: headers,
                      #cancelToken: cancelToken,
                      #retry: retry,
                    },
                  ),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<List<T>> getList<T>(
    String? path, {
    required _i4.FromJson<T>? fromJson,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
    bool? retry = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getList,
              [path],
              {
                #fromJson: fromJson,
                #queryParameters: queryParameters,
                #headers: headers,
                #cancelToken: cancelToken,
                #retry: retry,
              },
            ),
            returnValue: _i3.Future<List<T>>.value(<T>[]),
          )
          as _i3.Future<List<T>>);

  @override
  _i3.Future<T> post<T>(
    String? path, {
    required _i4.FromJson<T>? fromJson,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
    bool? retry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #fromJson: fromJson,
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
                #cancelToken: cancelToken,
                #retry: retry,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #post,
                      [path],
                      {
                        #fromJson: fromJson,
                        #data: data,
                        #queryParameters: queryParameters,
                        #headers: headers,
                        #cancelToken: cancelToken,
                        #retry: retry,
                      },
                    ),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(
                    #post,
                    [path],
                    {
                      #fromJson: fromJson,
                      #data: data,
                      #queryParameters: queryParameters,
                      #headers: headers,
                      #cancelToken: cancelToken,
                      #retry: retry,
                    },
                  ),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<T> put<T>(
    String? path, {
    required _i4.FromJson<T>? fromJson,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
    bool? retry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #fromJson: fromJson,
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
                #cancelToken: cancelToken,
                #retry: retry,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #put,
                      [path],
                      {
                        #fromJson: fromJson,
                        #data: data,
                        #queryParameters: queryParameters,
                        #headers: headers,
                        #cancelToken: cancelToken,
                        #retry: retry,
                      },
                    ),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(
                    #put,
                    [path],
                    {
                      #fromJson: fromJson,
                      #data: data,
                      #queryParameters: queryParameters,
                      #headers: headers,
                      #cancelToken: cancelToken,
                      #retry: retry,
                    },
                  ),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<T> patch<T>(
    String? path, {
    required _i4.FromJson<T>? fromJson,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
    bool? retry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #fromJson: fromJson,
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
                #cancelToken: cancelToken,
                #retry: retry,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #patch,
                      [path],
                      {
                        #fromJson: fromJson,
                        #data: data,
                        #queryParameters: queryParameters,
                        #headers: headers,
                        #cancelToken: cancelToken,
                        #retry: retry,
                      },
                    ),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(
                    #patch,
                    [path],
                    {
                      #fromJson: fromJson,
                      #data: data,
                      #queryParameters: queryParameters,
                      #headers: headers,
                      #cancelToken: cancelToken,
                      #retry: retry,
                    },
                  ),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<T> delete<T>(
    String? path, {
    required _i4.FromJson<T>? fromJson,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
    bool? retry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #fromJson: fromJson,
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
                #cancelToken: cancelToken,
                #retry: retry,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #delete,
                      [path],
                      {
                        #fromJson: fromJson,
                        #data: data,
                        #queryParameters: queryParameters,
                        #headers: headers,
                        #cancelToken: cancelToken,
                        #retry: retry,
                      },
                    ),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(
                    #delete,
                    [path],
                    {
                      #fromJson: fromJson,
                      #data: data,
                      #queryParameters: queryParameters,
                      #headers: headers,
                      #cancelToken: cancelToken,
                      #retry: retry,
                    },
                  ),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<void> postUnit(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
    bool? retry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUnit,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
                #cancelToken: cancelToken,
                #retry: retry,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteUnit(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
    bool? retry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUnit,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
                #cancelToken: cancelToken,
                #retry: retry,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> putUnit(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
    bool? retry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUnit,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
                #cancelToken: cancelToken,
                #retry: retry,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<T> upload<T>(
    String? path, {
    required _i4.FromJson<T>? fromJson,
    required _i2.FormData? formData,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.ProgressCallback? onSendProgress,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upload,
              [path],
              {
                #fromJson: fromJson,
                #formData: formData,
                #queryParameters: queryParameters,
                #headers: headers,
                #onSendProgress: onSendProgress,
                #cancelToken: cancelToken,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #upload,
                      [path],
                      {
                        #fromJson: fromJson,
                        #formData: formData,
                        #queryParameters: queryParameters,
                        #headers: headers,
                        #onSendProgress: onSendProgress,
                        #cancelToken: cancelToken,
                      },
                    ),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(
                    #upload,
                    [path],
                    {
                      #fromJson: fromJson,
                      #formData: formData,
                      #queryParameters: queryParameters,
                      #headers: headers,
                      #onSendProgress: onSendProgress,
                      #cancelToken: cancelToken,
                    },
                  ),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<void> download(
    String? urlPath,
    String? savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    bool? deleteOnError = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i2.CancelToken createCancelToken() =>
      (super.noSuchMethod(
            Invocation.method(#createCancelToken, []),
            returnValue: _FakeCancelToken_2(
              this,
              Invocation.method(#createCancelToken, []),
            ),
          )
          as _i2.CancelToken);

  @override
  void updateBaseUrl(String? newBaseUrl) => super.noSuchMethod(
    Invocation.method(#updateBaseUrl, [newBaseUrl]),
    returnValueForMissingStub: null,
  );

  @override
  void addInterceptor(_i2.Interceptor? interceptor) => super.noSuchMethod(
    Invocation.method(#addInterceptor, [interceptor]),
    returnValueForMissingStub: null,
  );

  @override
  void clearInterceptors() => super.noSuchMethod(
    Invocation.method(#clearInterceptors, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateHeaders(Map<String, dynamic>? headers) => super.noSuchMethod(
    Invocation.method(#updateHeaders, [headers]),
    returnValueForMissingStub: null,
  );

  @override
  void removeHeader(String? key) => super.noSuchMethod(
    Invocation.method(#removeHeader, [key]),
    returnValueForMissingStub: null,
  );
}
