// Mocks generated by Mockito 5.4.6 from annotations
// in meno/test/features/auth/auth_error_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i8;
import 'package:firebase_messaging/firebase_messaging.dart' as _i3;
import 'package:logger/logger.dart' as _i2;
import 'package:meno/_shared/_shared.dart' as _i12;
import 'package:meno/features/auth/model/_model.dart' as _i10;
import 'package:meno/features/auth/model/dtos/_dtos.dart' as _i6;
import 'package:meno/features/auth/services/auth_http_service.dart' as _i4;
import 'package:meno/features/auth/services/auth_local_service.dart' as _i9;
import 'package:meno/features/onboarding/services/onboarding_service.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationSettings_1 extends _i1.SmartFake
    implements _i3.NotificationSettings {
  _FakeNotificationSettings_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthHttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthHttpService extends _i1.Mock implements _i4.AuthHttpService {
  MockAuthHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.UserCredentialDto> login({
    required String? email,
    required String? password,
    String? pushNotificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #email: email,
              #password: password,
              #pushNotificationToken: pushNotificationToken,
            }),
            returnValue: _i5.Future<_i6.UserCredentialDto>.value(
              _i7.dummyValue<_i6.UserCredentialDto>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                  #pushNotificationToken: pushNotificationToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.UserCredentialDto>);

  @override
  _i5.Future<_i6.UserCredentialDto> register({
    required String? fullName,
    required String? email,
    required String? password,
    String? pushNotificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #fullName: fullName,
              #email: email,
              #password: password,
              #pushNotificationToken: pushNotificationToken,
            }),
            returnValue: _i5.Future<_i6.UserCredentialDto>.value(
              _i7.dummyValue<_i6.UserCredentialDto>(
                this,
                Invocation.method(#register, [], {
                  #fullName: fullName,
                  #email: email,
                  #password: password,
                  #pushNotificationToken: pushNotificationToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.UserCredentialDto>);

  @override
  _i5.Future<_i6.UserCredentialDto> googleSignIn({
    required String? idToken,
    String? pushNotificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#googleSignIn, [], {
              #idToken: idToken,
              #pushNotificationToken: pushNotificationToken,
            }),
            returnValue: _i5.Future<_i6.UserCredentialDto>.value(
              _i7.dummyValue<_i6.UserCredentialDto>(
                this,
                Invocation.method(#googleSignIn, [], {
                  #idToken: idToken,
                  #pushNotificationToken: pushNotificationToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.UserCredentialDto>);

  @override
  _i5.Future<_i6.UserCredentialDto> googleSignUp({
    required String? idToken,
    String? pushNotificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#googleSignUp, [], {
              #idToken: idToken,
              #pushNotificationToken: pushNotificationToken,
            }),
            returnValue: _i5.Future<_i6.UserCredentialDto>.value(
              _i7.dummyValue<_i6.UserCredentialDto>(
                this,
                Invocation.method(#googleSignUp, [], {
                  #idToken: idToken,
                  #pushNotificationToken: pushNotificationToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.UserCredentialDto>);

  @override
  _i5.Future<void> verifyEmail({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#email: email, #code: code}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetPassword({
    required String? email,
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> requestOtp({
    required String? email,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestOtp, [], {#email: email, #type: type}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUser([_i8.CancelToken? cancelToken]) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [cancelToken]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AuthLocalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalService extends _i1.Mock implements _i9.AuthLocalService {
  MockAuthLocalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.UserCredentialDto?> get onCredentialChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onCredentialChanged),
            returnValue: _i5.Stream<_i6.UserCredentialDto?>.empty(),
          )
          as _i5.Stream<_i6.UserCredentialDto?>);

  @override
  _i5.Future<void> saveCredential(_i6.UserCredentialDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredential, [dto]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.UserCredentialDto?> getCredential() =>
      (super.noSuchMethod(
            Invocation.method(#getCredential, []),
            returnValue: _i5.Future<_i6.UserCredentialDto?>.value(),
          )
          as _i5.Future<_i6.UserCredentialDto?>);

  @override
  _i5.Future<void> clearCredential() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredential, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i10.Session?> getSession() =>
      (super.noSuchMethod(
            Invocation.method(#getSession, []),
            returnValue: _i5.Future<_i10.Session?>.value(),
          )
          as _i5.Future<_i10.Session?>);

  @override
  _i5.Future<void> updateSession(_i10.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [session]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> switchActiveUser(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#switchActiveUser, [targetUserId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, _i6.UserCredentialDto>> getAllAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAccounts, []),
            returnValue: _i5.Future<Map<String, _i6.UserCredentialDto>>.value(
              <String, _i6.UserCredentialDto>{},
            ),
          )
          as _i5.Future<Map<String, _i6.UserCredentialDto>>);

  @override
  _i5.Future<void> removeAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [OnboardingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingService extends _i1.Mock implements _i11.OnboardingService {
  MockOnboardingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnboarded =>
      (super.noSuchMethod(Invocation.getter(#isOnboarded), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> completeOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#completeOnboarding, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [PushNotificationsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushNotificationsService extends _i1.Mock
    implements _i12.PushNotificationsService {
  MockPushNotificationsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.RemoteMessage> get onMessage =>
      (super.noSuchMethod(
            Invocation.getter(#onMessage),
            returnValue: _i5.Stream<_i3.RemoteMessage>.empty(),
          )
          as _i5.Stream<_i3.RemoteMessage>);

  @override
  _i5.Stream<String> get onTokenRefresh =>
      (super.noSuchMethod(
            Invocation.getter(#onTokenRefresh),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<_i3.RemoteMessage> get onMessageOpenedApp =>
      (super.noSuchMethod(
            Invocation.getter(#onMessageOpenedApp),
            returnValue: _i5.Stream<_i3.RemoteMessage>.empty(),
          )
          as _i5.Stream<_i3.RemoteMessage>);

  @override
  _i2.Logger get log =>
      (super.noSuchMethod(
            Invocation.getter(#log),
            returnValue: _FakeLogger_0(this, Invocation.getter(#log)),
          )
          as _i2.Logger);

  @override
  _i5.Future<_i3.NotificationSettings> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i5.Future<_i3.NotificationSettings>.value(
              _FakeNotificationSettings_1(
                this,
                Invocation.method(#requestPermissions, []),
              ),
            ),
          )
          as _i5.Future<_i3.NotificationSettings>);

  @override
  _i5.Future<_i3.RemoteMessage?> getInitialMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialMessage, []),
            returnValue: _i5.Future<_i3.RemoteMessage?>.value(),
          )
          as _i5.Future<_i3.RemoteMessage?>);

  @override
  _i5.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);
}
