// Mocks generated by Mockito 5.4.6 from annotations
// in meno/test/features/auth/auth_local_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:meno/_shared/services/secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i2.SecureStorage {
  MockSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i2.StorageEvent> get onChange =>
      (super.noSuchMethod(
            Invocation.getter(#onChange),
            returnValue: _i3.Stream<_i2.StorageEvent>.empty(),
          )
          as _i3.Stream<_i2.StorageEvent>);

  @override
  _i3.Stream<String?> watchKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#watchKey, [key]),
            returnValue: _i3.Stream<String?>.empty(),
          )
          as _i3.Stream<String?>);

  @override
  _i3.Stream<Map<String, String?>> watchKeys(List<String>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#watchKeys, [keys]),
            returnValue: _i3.Stream<Map<String, String?>>.empty(),
          )
          as _i3.Stream<Map<String, String?>>);

  @override
  void setCacheEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setCacheEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<String?> read(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> write(String? key, {required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key], {#value: value}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> writeBatch(Map<String, String?>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#writeBatch, [entries]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String?>> readBatch(List<String>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#readBatch, [keys]),
            returnValue: _i3.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i3.Future<Map<String, String?>>);

  @override
  _i3.Future<void> deleteBatch(List<String>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBatch, [keys]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, String>> readAll() =>
      (super.noSuchMethod(
            Invocation.method(#readAll, []),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
