// Mocks generated by Mockito 5.4.6 from annotations
// in meno/test/features/auth/auth_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i6;
import 'package:meno/features/auth/model/dtos/dtos.dart' as _i4;
import 'package:meno/features/auth/model/model.dart' as _i8;
import 'package:meno/features/auth/services/auth_http_service.dart' as _i2;
import 'package:meno/features/auth/services/auth_local_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthHttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthHttpService extends _i1.Mock implements _i2.AuthHttpService {
  MockAuthHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserCredentialDto> login({
    required String? email,
    required String? password,
    String? pushNotificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #email: email,
              #password: password,
              #pushNotificationToken: pushNotificationToken,
            }),
            returnValue: _i3.Future<_i4.UserCredentialDto>.value(
              _i5.dummyValue<_i4.UserCredentialDto>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                  #pushNotificationToken: pushNotificationToken,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.UserCredentialDto>);

  @override
  _i3.Future<_i4.UserCredentialDto> register({
    required String? fullName,
    required String? email,
    required String? password,
    String? pushNotificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #fullName: fullName,
              #email: email,
              #password: password,
              #pushNotificationToken: pushNotificationToken,
            }),
            returnValue: _i3.Future<_i4.UserCredentialDto>.value(
              _i5.dummyValue<_i4.UserCredentialDto>(
                this,
                Invocation.method(#register, [], {
                  #fullName: fullName,
                  #email: email,
                  #password: password,
                  #pushNotificationToken: pushNotificationToken,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.UserCredentialDto>);

  @override
  _i3.Future<_i4.UserCredentialDto> googleSignIn({
    required String? idToken,
    String? pushNotificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#googleSignIn, [], {
              #idToken: idToken,
              #pushNotificationToken: pushNotificationToken,
            }),
            returnValue: _i3.Future<_i4.UserCredentialDto>.value(
              _i5.dummyValue<_i4.UserCredentialDto>(
                this,
                Invocation.method(#googleSignIn, [], {
                  #idToken: idToken,
                  #pushNotificationToken: pushNotificationToken,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.UserCredentialDto>);

  @override
  _i3.Future<_i4.UserCredentialDto> googleSignUp({
    required String? idToken,
    String? pushNotificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#googleSignUp, [], {
              #idToken: idToken,
              #pushNotificationToken: pushNotificationToken,
            }),
            returnValue: _i3.Future<_i4.UserCredentialDto>.value(
              _i5.dummyValue<_i4.UserCredentialDto>(
                this,
                Invocation.method(#googleSignUp, [], {
                  #idToken: idToken,
                  #pushNotificationToken: pushNotificationToken,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.UserCredentialDto>);

  @override
  _i3.Future<void> verifyEmail({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#email: email, #code: code}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetPassword({
    required String? email,
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> requestOtp({
    required String? email,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestOtp, [], {#email: email, #type: type}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteUser([_i6.CancelToken? cancelToken]) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [cancelToken]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AuthLocalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalService extends _i1.Mock implements _i7.AuthLocalService {
  MockAuthLocalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.UserCredentialDto?> get onCredentialChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onCredentialChanged),
            returnValue: _i3.Stream<_i4.UserCredentialDto?>.empty(),
          )
          as _i3.Stream<_i4.UserCredentialDto?>);

  @override
  _i3.Future<void> saveCredential(_i4.UserCredentialDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredential, [dto]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.UserCredentialDto?> getCredential() =>
      (super.noSuchMethod(
            Invocation.method(#getCredential, []),
            returnValue: _i3.Future<_i4.UserCredentialDto?>.value(),
          )
          as _i3.Future<_i4.UserCredentialDto?>);

  @override
  _i3.Future<void> clearCredential() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredential, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i8.Session?> getSession() =>
      (super.noSuchMethod(
            Invocation.method(#getSession, []),
            returnValue: _i3.Future<_i8.Session?>.value(),
          )
          as _i3.Future<_i8.Session?>);

  @override
  _i3.Future<void> updateSession(_i8.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [session]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> switchActiveUser(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#switchActiveUser, [targetUserId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i4.UserCredentialDto>> getAllAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAccounts, []),
            returnValue: _i3.Future<Map<String, _i4.UserCredentialDto>>.value(
              <String, _i4.UserCredentialDto>{},
            ),
          )
          as _i3.Future<Map<String, _i4.UserCredentialDto>>);

  @override
  _i3.Future<void> removeAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
