// Mocks generated by Mockito 5.4.2 from annotations
// in meno_fe_v1/test/features/auth/infrastructure/auth_facade_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:meno_fe_v1/features/auth/infrastructure/datasources/auth_local_datasource.dart'
    as _i7;
import 'package:meno_fe_v1/features/auth/infrastructure/datasources/auth_remote_datasource.dart'
    as _i3;
import 'package:meno_fe_v1/features/auth/infrastructure/dtos/user_credentials_dto.dart'
    as _i5;
import 'package:meno_fe_v1/features/auth/infrastructure/mapper/auth_mapper.dart'
    as _i8;
import 'package:meno_fe_v1/features/auth/infrastructure/responses/auth_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0<T> extends _i1.SmartFake
    implements _i2.AuthResponse<T> {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i3.AuthRemoteDatasource {
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>> googleLogin(
          String? idToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #googleLogin,
          [idToken],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
            _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #googleLogin,
            [idToken],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #googleLogin,
            [idToken],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>> googleRegister(
          String? idToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #googleRegister,
          [idToken],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
            _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #googleRegister,
            [idToken],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #googleRegister,
            [idToken],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
            _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>> register({
    required String? fullName,
    required String? email,
    required String? password,
    String? bio,
    _i6.File? image,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #fullName: fullName,
            #email: email,
            #password: password,
            #bio: bio,
            #image: image,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
            _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #fullName: fullName,
              #email: email,
              #password: password,
              #bio: bio,
              #image: image,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #fullName: fullName,
              #email: email,
              #password: password,
              #bio: bio,
              #image: image,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>);
}

/// A class which mocks [AuthLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDatasource extends _i1.Mock
    implements _i7.AuthLocalDatasource {
  @override
  _i4.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteUserCredentials() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserCredentials,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteUserToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserToken,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i5.UserCredentialsDto?> getUserCredentials() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCredentials,
          [],
        ),
        returnValue: _i4.Future<_i5.UserCredentialsDto?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.UserCredentialsDto?>.value(),
      ) as _i4.Future<_i5.UserCredentialsDto?>);
  @override
  _i4.Future<String?> getUserToken() => (super.noSuchMethod(
        Invocation.method(
          #getUserToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
  @override
  _i4.Future<void> storeToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #storeToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> storeUserCredentials(_i5.UserCredentialsDto? dto) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeUserCredentials,
          [dto],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AuthMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthMapper extends _i1.Mock implements _i8.AuthMapper {}
